config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  get "users/check_email" =>"users#check_email"
  get "sessions/check_email" =>"sessions#check_email"
  resources :users
  resources :sessions, except: :show
  resources :dashboards

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password :validations => false

 validates :name, presence: true

 validates :email,
 :presence => true,
 :uniqueness => {:case_sensitive => false},
 :format => {:with => ConfigCenter::GeneralValidations::EMAIL_FORMAT_REG_EXP}

 validates :password, :presence => true,
 :length => {:minimum => 6}


 def self.authenticate(email, password)
  user = find_by_email(email)
  if user && user.password_digest == BCrypt::Engine.hash_secret(password, user.password_digest)
    user
  else
    nil
  end
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
  	@current_user ||= User.find_by_id(session[:user_id])
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

	def new
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
  respond_to do |format|
    format.js{}
  end
end
def check_email
  @user = User.find_by_email(params[:email])
  respond_to do |format|
    format.json { render :json => @user.present? }

  end
end

def create
  if params[:provider] == "google_oauth2"
    auth = request.env["omniauth.auth"]
    user = User.where(:provider => auth['provider'],
      :uid => auth['uid'].to_s).first || User.create_with_omniauth(auth)
  else
    user = User.authenticate(params[:email], params[:password])
  end
  if user
    session[:user_id] = user.id
    flash[:success] = "Signed in Successfully"
    redirect_to new_dashboard_path, :success => "Logged in!"
  else
    flash[:alert] = "Invalid email or password"
    redirect_to root_path
  end
end

def destroy
  session[:user_id] = nil
  redirect_to root_path
  flash[:alert] = "Logged out!"
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	skip_before_filter :require_login

  def check_email
    @user = User.find_by_email(params[:user][:email])

    respond_to do |format|
      format.json { render :json => !@user  }
    end
  end

  def new
    @user = User.new
    respond_to do |format|
      format.js{}
    end
  end

  def create
    @user = User.new(user_params)
    user_name = user_params[:name].titleize
    @user.name = user_name
    if @user.valid? && @user.errors.blank?
      @user.save
      @success = true
      session[:user_id] = @user.id
      redirect_to new_dashboard_path
      flash[:success] = "You have been logged in successfully!"
    else
      @success = false
      redirect_to root_path
      flash[:error] = "Failed to sign up!"
    end

  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboards/new.html.erb
<div class="container landing-content-area">
<div class="input-group search-margin">
    <input type="text" id="menu_search" class="form-control" placeholder="Search here ..">
      <span class="input-group-btn">
        <button class="btn btn-default filter-btn" type="button">
          <i class="fa fa-search" aria-hidden="true"></i>
        </button>
      </span>
    </div>
	<h1 class="landing-heding">Dashboard </h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Assignment</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body class="landing-page-bg">
	<%= render partial: 'layouts/common/header'  %>
	<div id="div_flash_message" class="container">
    <%= render :partial=>"/layouts/common/flash_messages" -%>
  </div>
  <%= yield %>
  <div id="popup_modal" class="modal fade"></div>
  <div id="stack2" class="modal fade"></div>

</body>
</html>

app/views/layouts/common/_flash_messages.html.erb
 <%
 if request.xhr?
 	flash_message = flash.now[:success] || flash.now[:notice] || flash.now[:alert] || flash.now[:error]
 	style_classes = ""
 else
 	style_classes = ""
 	flash_message = flash[:success] || flash[:notice] || flash[:alert] || flash[:error]
 end
 cls_name = "alert-info"
 cls_name = 'alert-success' if flash.now[:success] || flash[:success]
 cls_name = 'alert-warning' if flash.now[:alert] || flash[:alert]
 cls_name = 'alert-danger' if flash.now[:error] || flash[:error]

 flash_message = flash_message.strip if flash_message

 %>

 <% unless flash_message.blank? %>
 <div id = "flash">
 	<div class="<%= style_classes %> alert <%= cls_name %> fade in mb-10" data-alert="alert">
 		<a class="close" data-dismiss='alert' href="#">×</a>
 		<p><%= flash_message %></p>
 	</div>
 </div>
 <% end %>

app/views/layouts/common/_footer.html.erb
<script src="assets/js/jquery.js"></script>
<script src="assets/js/bootstrap.js"></script>

app/views/layouts/common/_header.html.erb
<!--    Header-->
<nav class="navbar navbar-inverse ">
  <div class="container">
    <div class="navbar-header">
      <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%#= link_to "Interactive-Forum", home_path, :class => "navbar-brand" %>
    </div>
    <div class="navbar-collapse collapse">

      <ul class="nav navbar-nav navbar-right">

        <% if current_user %>
        <li>
          <img src="/assets/Profile-Pic.jpg"class="img-rounded profile-pic">
        </li>
        <li>
          <h3 class="sharmila"><%= current_user.name %></h3>
        </li>

        <li>
          <%= button_to "Sign out", session_path(:id => current_user.id),:method=> :delete, :class=>"btn btn-success signup-login-btn", 'data-toggle' => 'modal', 'data-target'=>'#myModal'%></li>
          <% else %>

          <li>
            <%= button_to "Sign up", new_user_path ,:method=> :get, remote: true, :class=>"btn btn-success signup-login-btn", 'data-toggle' => 'modal', 'data-target'=>'#myModal'%>
          </li>
          <li>

            <%= button_to "Sign in", new_session_path ,:method=> :get, remote: true, :class=>"btn btn-success signup-login-btn", 'data-toggle' => 'modal', 'data-target'=>'#myModal'%>

          </li>

          <% end %>

        </ul>
      </div>
    </div>

  </nav>

app/views/layouts/common/_signin_modal.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title">Log In</h4>
    </div>
    <%= form_tag sessions_path , :class =>"form-horizontal", :id =>"sign_in", :method=> :post, authenticity_token: true  do |f| %>

    <div class="modal-body">

      <form class="form-horizontal">
        <div class="form-group">
          <label for="inputEmail" class="col-sm-3 control-label">Email id</label>
          <div class="col-sm-7">
            <%= text_field_tag :email,nil, :class =>"form-control",:id =>"inputemail", :placeholder => "email" %>
          </div>
          <div class="col-sm-2"></div>
        </div>
        <div class="form-group">
          <label for="inputPassword" class="col-sm-3 control-label">Password</label>
          <div class="col-sm-7">
            <%= password_field_tag :password,nil, :class =>"form-control",:id =>"inputPassword",:placeholder => "Password" %>
          </div>
          <div class="col-sm-2"></div>
        </div>
      </div>
      <div class="modal-footer">
        <%= submit_tag "Submit", :class =>"btn btn-primary ok-btn-padding" %>
        <button type="button" class="btn btn-default ok-btn-padding" data-dismiss="modal">Cancel</button>
        <br>
      </br>
      <center> <%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %>
      </center>

    </div>
    <% end %>
  </div>
</div>
</div>

app/views/layouts/common/_signup_modal.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title">Sign Up</h4>
    </div>
    <div class="modal-body">
      <%= form_for @user, remote: true, method: :post, authenticity_token: true, html:{:class =>"form-horizontal", :id=>"register" } do |f| %>
      <div class="form-group">
        <label for="Name" class="col-sm-3 control-label">Name<span class="condition">*</span></label>
        <div class="col-sm-7">
          <%= f.text_field :name, :class=>"form-control", :placeholder=>"Name"%>
        </div>
        <div class="col-sm-2"></div>
      </div>
      <div class="form-group">
        <label for="inputEmail" class="col-sm-3 control-label">Email id<span class="condition">*</span></label>
        <div class="col-sm-7">
          <%= f.text_field :email, :class=>"form-control",:id=>"user_email", :placeholder=>"Email"%>
        </div>
        <div class="col-sm-2"></div>
      </div>
      <div class="form-group">
        <label for="inputPassword" class="col-sm-3 control-label">Password<span class="condition">*</span></label>
        <div class="col-sm-7">
          <%= f.password_field :password, :class=>"form-control", :placeholder=>"Password"%>
        </div>
        <div class="col-sm-2"></div>
      </div>
      <div class="form-group">
        <label for="inputPassword" class="col-sm-3 control-label">Confirm<span class="condition">*</span></label>
        <div class="col-sm-7">
          <%= f.password_field :password_confirmation, :class=>"form-control", :placeholder=>"confirmation password"%>
        </div>
      </div>
      <div class="modal-footer">
       <%= f.submit "OK", :class=>"btn btn-primary ok-btn-padding" %>
       <button type="button" class="btn btn-default ok-btn-padding" data-dismiss="modal">Cancel</button>
       <%end%>
     </div>
   </div>
 </div>
</div>

app/views/users/index.html.erb
<div class="container landing-content-area">
	<h1 class="landing-heding">ASSIGNMENT</h1>
	<h5>  BY SHARMILA</h5>
</div>

app/views/users/new.js.erb
$('#popup_modal').html("<%= escape_javascript(render(:partial=>'layouts/common/signup_modal')) %>");
$('#popup_modal').modal('show');
UserValidator();